AWSTemplateFormatVersion: "2010-09-09"
Resources:
  tweetTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: "SearchText"
          AttributeType: "S"
        - 
          AttributeName: "Id"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "SearchText"
          KeyType: "HASH"
        - 
          AttributeName: "Id"
          KeyType: "RANGE"

      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "tweetTable"
